# Taken from https://github.com/BretFisher/jekyll-serve (MIT License)
version: '2.4'

services:
  jekyll:
    image: bretfisher/jekyll-serve
    volumes:
      - .:/site
    ports:
      - '8080:4000'
